update shell config

diff --git a/shell/global/profile b/shell/global/profile
--- a/shell/global/profile
+++ b/shell/global/profile
@@ -3,7 +3,7 @@
 # -- -- -- -- -- -- -- -- -- -- -- #
 # --        /etc/profile        -- #
 # -- -- -- -- -- -- -- -- -- -- -- #
-if [ "${BASH-no}" != "no" ]; then
-	[ -r "/etc/bashrc" ] && . "/etc/bashrc"
+if [ "$SHELL" == *"bash"* ]; then
+	[ -r "/etc/bashrc" ] && source "/etc/bashrc" || echo "!!! '/etc/bashrc' not found !!!"
 fi
 
